name: Deploy Website

on:
  push:
    branches:
      - portfolio

  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Source Branch Checkout
        uses: actions/checkout@v3
        with:
          ref: portfolio

      - name: Deploy from output to main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: main
          force_orphan: true
